#!/usr/bin/env python
import os
import sys
from selenium import webdriver

def take_screenshot(driver, name, save_location):
  # Make sure the path exists.
  path = os.path.abspath(save_location)
  if not os.path.exists(path):
    os.makedirs(path)
  full_path = '%s/%s' % (path, name)
  driver.get_screenshot_as_file(full_path)
  return full_path

print sys.argv
print len(sys.argv)
driver = webdriver.PhantomJS()  # or add to your PATH
driver.set_window_size(1024, 768)  # optional
driver.get(sys.argv[1])
last_height = driver.execute_script("return document.body.scrollHeight")
driver.set_window_size(1024, last_height)  # optional
screenshot = take_screenshot(driver, driver.title+'.png', '/Users/zyang/Documents/ddweb')
print last_height
print screenshot

# driver.save_screenshot('screen.png')  # save a screenshot to disk
# sbtn = driver.find_element_by_css_selector('button.gbqfba')
# sbtn.click()

# count = 0
# while count < length:
#     def execute(script, args):
#         driver.execute('executePhantomScript', {'script': script, 'args' : args })
#
#     driver = webdriver.PhantomJS('phantomjs')
#
#     # hack while the python interface lags
#     driver.command_executor._commands['executePhantomScript'] = ('POST',     '/session/$sessionId/phantom/execute')
#
#     driver.get(urls[count])
#
#     # set page format
#     # inside the execution script, webpage is "this"
#     pageFormat = '''this.paperSize = {format: "A4", orientation: "portrait" };'''
#     execute(pageFormat, [])
#
#     # render current page
#     render = '''this.render("test.pdf")'''
#     render = 'this.render("{file_name}.pdf")'.format(file_name=names[count])
#     execute(render, [])
#
#     count+=1